MBTA_STOPS = {
"Government Center" : "place-gover",
"Park Street" : "place-pktrm",
"Boylston" : "place-boyls",
"Arlington" : "place-armnl",
"Copley" : "place-coecl",
"Hynes Convention Center" : "place-hymnl",
"Kenmore" : "place-kencl",
"Blandford Street" : "place-bland",
"Boston University East" : "place-buest",
"Boston University Central" : "place-bucen",
"Amory Street" : "place-amory",
"Babcock Street" : "place-babck",
"Packard's Corner" : "place-brico",
"Harvard Avenue" : "place-harvd",
"Griggs Street" : "place-grigg",
"Allston Street" : "place-alsgr",
"Warren Street" : "place-wrnst",
"Washington Street" : "place-wascm",
"Sutherland Road" : "place-sthld",
"Chiswick Road" : "place-chswk",
"Chestnut Hill Avenue" : "place-chill",
"South Street" : "place-sougr",
"Boston College" : "place-lake",
"Cleveland Circle" : "place-clmnl",
"Englewood Avenue" : "place-engav",
"Dean Road" : "place-denrd",
"Tappan Street" : "place-tapst",
"Washington Square" : "place-bcnwa",
"Fairbanks Street" : "place-fbkst",
"Brandon Hall" : "place-bndhl",
"Summit Avenue" : "place-sumav",
"Coolidge Corner" : "place-cool",
"Saint Paul Street" : "place-stpul",
"Kent Street" : "place-kntst",
"Hawes Street" : "place-hwsst",
"Saint Mary's Street" : "place-smary",
"Riverside" : "place-river",
"Woodland" : "place-woodl",
"Waban" : "place-waban",
"Eliot" : "place-eliot",
"Newton Highlands" : "place-newtn",
"Newton Centre" : "place-newto",
"Chestnut Hill" : "place-chhil",
"Reservoir" : "place-rsmnl",
"Beaconsfield" : "place-bcnfd",
"Brookline Hills" : "place-brkhl",
"Brookline Village" : "place-bvmnl",
"Longwood" : "place-longw",
"Fenway" : "place-fenwy",
"Haymarket" : "place-haecl",
"North Station" : "place-north",
"Science Park/West End" : "place-spmnl",
"Lechmere" : "place-lech",
"Union Square" : "place-unsqu",
"Heath Street" : "place-hsmnl",
"Back of the Hill" : "place-bckhl",
"Riverway" : "place-rvrwy",
"Mission Park" : "place-mispk",
"Fenwood Road" : "place-fenwd",
"Brigham Circle" : "place-brmnl",
"Longwood Medical Area" : "place-lngmd",
"Museum of Fine Arts" : "place-mfa",
"Northeastern University" : "place-nuniv",
"Symphony" : "place-symcl",
"Prudential" : "place-prmnl",
"Forest Hills" : "place-forhl",
"Green Street" : "place-grnst",
"Stony Brook" : "place-sbmnl",
"Jackson Square" : "place-jaksn",
"Roxbury Crossing" : "place-rcmnl",
"Ruggles" : "place-rugg",
"Massachusetts Avenue" : "place-masta",
"Back Bay" : "place-bbsta",
"Tufts Medical Center" : "place-tumnl",
"Chinatown" : "place-chncl",
"Downtown Crossing" : "place-dwnxg",
"State" : "place-state",
"Community College" : "place-ccmnl",
"Sullivan Square" : "place-sull",
"Assembly" : "place-astao",
"Wellington" : "place-welln",
"Malden Center" : "place-mlmnl",
"Oak Grove" : "place-ogmnl",
"Alewife" : "place-alfcl",
"Davis" : "place-davis",
"Porter" : "place-portr",
"Harvard" : "place-harsq",
"Central" : "place-cntsq",
"Kendall/MIT" : "place-knncl",
"Charles/MGH" : "place-chmnl",
"South Station" : "place-sstat",
"Broadway" : "place-brdwy",
"Andrew" : "place-andrw",
"JFK/UMass" : "place-jfk",
"Savin Hill" : "place-shmnl",
"Fields Corner" : "place-fldcr",
"Shawmut" : "place-smmnl",
"Ashmont" : "place-asmnl",
"North Quincy" : "place-nqncy",
"Wollaston" : "place-wlsta",
"Quincy Center" : "place-qnctr",
"Quincy Adams" : "place-qamnl",
"Braintree" : "place-brntn",
"Bowdoin" : "place-bomnl",
"Aquarium" : "place-aqucl",
"Maverick" : "place-mvbcl",
"Airport" : "place-aport",
"Wood Island" : "place-wimnl",
"Orient Heights" : "place-orhte",
"Suffolk Downs" : "place-sdmnl",
"Beachmont" : "place-bmmnl",
"Revere Beach" : "place-rbmnl",
"Wonderland" : "place-wondl"
}


DESTINATION_STOPS = {
        "Wonderland" : "WNDERLAND",
        "Oak Grove" : "OAK GROVE",
        "Government Center" : "GOV CENTR",
        "Alewife" : "ALEWIFE  ",
        "Boston College" : "BOS CLLEG",
        "Cleveland Circle" : "CLVLND CR",
        "Riverside" : "RIVERSIDE",
        "Heath Street" : "HEATH    ",
        "Forest Hills" : "FORST HL",
        "Mattapan" : "MATTAPAM ",
        "Braintree" : "BRAINTREE",
        "Ashmont/Braintree" : "ASH/BRAIN",
        "South Station" : "STH STATN",
        "Union Square" : "UNIN SQRE",
        "Bowdoin" : "BOWDOIN  "
    }